import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, ChevronDown, Download, FileText, Pencil, Plus, ReceiptText, RotateCcw, Save, Trash2, Truck, Wallet, X } from 'lucide-react';
import { api } from '../api.js';
import { useBranch } from '../contexts/BranchContext.jsx';
import { alertError, confirmAction, toastSuccess } from '../utils/alerts.js';
import './tripFinance.css';

const costs = [
  ['sand_cost','ค่าซื้อทราย'],['stone_cost','ค่าซื้อหิน'],['fuel_cost','ค่าน้ำมัน'],['tire_cost','ค่ายาง'],
  ['parts_cost','ค่าอะไหล่'],['mechanic_cost','ค่าแรงช่างซ่อม'],['driver_cost','ค่าแรงคนขับ'],['other_cost','ค่าใช้จ่ายอื่น ๆ'],
];
const money = value => (Number(value || 0)/100).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const baht = value => Number(value || 0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const currentDate = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const defaultForm = () => ({date:currentDate(),vehicle_id:'',material:'',quantity:'',origin_place:'',destination_place:'',distance_km:'',reference:'',note:'',income_baht:'',...Object.fromEntries(costs.map(([key])=>[key,'']))});
function exportCsv(rows,period) {
  const columns=[['date','วันที่'],['plate_no','ทะเบียน'],['material','วัสดุ'],['quantity','จำนวน'],['origin_place','ต้นทาง'],['destination_place','ปลายทาง'],['distance_km','ระยะทาง (กม.)'],['reference','เลขที่เอกสาร'],['income_satang','รายรับ (บาท)'],...costs.map(([key,label])=>[`${key}_satang`,`${label} (บาท)`]),['expense_satang','รายจ่ายรวม (บาท)'],['profit_satang','กำไร/ขาดทุน (บาท)'],['note','หมายเหตุ']];
  const cell=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s=`'${s}`;return `"${s.replace(/"/g,'""')}"`;};
  const lines=[columns.map(([,label])=>cell(label)).join(','),...rows.map(r=>columns.map(([key])=>cell(key.endsWith('_satang')?(Number(r[key]||0)/100).toFixed(2):r[key])).join(','))];
  const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));
  const a=document.createElement('a');a.href=url;a.download=`kwanjai-trip-finance-${period}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function MoneyCard({label,value,kind}) {return <div className={`ktf-total ${kind}`}><span>{label}</span><strong>{money(value)} <small>บาท</small></strong></div>;}
function Field({label,children,className=''}) {return <label className={`ktf-field ${className}`}><span>{label}</span>{children}</label>;}
export default function TripFinancePage(){
  const {activeBranchId,activeBranch}=useBranch();
  const [mode,setMode]=useState('month');const [period,setPeriod]=useState(currentDate().slice(0,7));
  const [vehicleId,setVehicleId]=useState('all');const [data,setData]=useState(null);
  const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);
  const [editing,setEditing]=useState('');const [form,setForm]=useState(defaultForm);
  const editor=useRef(null);const loadSeq=useRef(0);
  const load=useCallback(async()=>{if(!activeBranchId)return;const seq=++loadSeq.current;setLoading(true);try{const result=await api.tripFinance(period);if(seq===loadSeq.current)setData(result);}catch(err){if(seq===loadSeq.current)alertError(err,'โหลดบัญชีต่อเที่ยวไม่สำเร็จ');}finally{if(seq===loadSeq.current)setLoading(false);}},[activeBranchId,period]);
  useEffect(()=>{load();return()=>{loadSeq.current++;};},[load]);
  const vehicles=data?.vehicles||[];
  const rows=useMemo(()=>vehicleId==='all'?(data?.rows||[]):(data?.rows||[]).filter(r=>r.vehicle_id===vehicleId),[data,vehicleId]);
  const summary=useMemo(()=>vehicleId==='all'?data?.total:(data?.by_vehicle||[]).find(v=>v.vehicle_id===vehicleId),[data,vehicleId])||{income_satang:0,expense_satang:0,profit_satang:0,trips:0};
  const field=(key,value)=>setForm(old=>({...old,[key]:value}));
  const costTotal=costs.reduce((sum,[key])=>sum+Math.round((Number(form[key])||0)*100),0);
  const income=Math.round((Number(form.income_baht)||0)*100);
  const reset=()=>{setEditing('');setForm({...defaultForm(),vehicle_id:vehicleId==='all'?'':vehicleId,date:mode==='month'&&period!==currentDate().slice(0,7)?`${period}-01`:currentDate()});};
  const edit=row=>{setEditing(row.id);setForm({date:row.date,vehicle_id:row.vehicle_id,material:row.material||'',quantity:row.quantity||'',origin_place:row.origin_place||'',destination_place:row.destination_place||'',distance_km:row.distance_km||'',reference:row.reference||'',note:row.note||'',income_baht:(Number(row.income_satang||0)/100).toFixed(2),...Object.fromEntries(costs.map(([key])=>[key,(Number(row[`${key}_satang`]||0)/100).toFixed(2)]))});editor.current?.scrollIntoView({behavior:'smooth',block:'start'});};
  const save=async e=>{e.preventDefault();if(saving)return;setSaving(true);try{if(editing)await api.updateTripFinance(editing,form);else await api.createTripFinance(form);toastSuccess(editing?'แก้ไขเที่ยวงานแล้ว':'บันทึกเที่ยวงานแล้ว');reset();await load();}catch(err){alertError(err,'บันทึกเที่ยวงานไม่สำเร็จ');}finally{setSaving(false);}};
  const remove=async row=>{if(!await confirmAction('ลบข้อมูลเที่ยวนี้?',`${row.date} · ${row.plate_no} · ${row.material}`))return;try{await api.deleteTripFinance(row.id);if(editing===row.id)reset();toastSuccess('ลบเที่ยวงานแล้ว');await load();}catch(err){alertError(err,'ลบเที่ยวงานไม่สำเร็จ');}};
  return <div className="ktf-page">
    <header className="ktf-hero"><div><span className="ktf-eyebrow"><ReceiptText size={16}/> ขวัญใจดาวทองขนส่ง · FINANCE</span><h1>บัญชีรายเที่ยว</h1><p>กรอกค่าขนส่งและต้นทุนทุกเที่ยว เห็นกำไรหรือขาดทุนทันที ก่อนสรุปยอดต่อคันรายเดือนและรายปี</p></div><img src="/kwanjai-logo.png" alt="ขวัญใจดาวทองขนส่ง"/></header>
    <section className="ktf-panel ktf-toolbar"><div className="ktf-periods"><button type="button" className={mode==='month'?'active':''} onClick={()=>{setMode('month');setPeriod(currentDate().slice(0,7));}}>รายเดือน</button><button type="button" className={mode==='year'?'active':''} onClick={()=>{setMode('year');setPeriod(currentDate().slice(0,4));}}>รายปี</button></div><Field label={mode==='month'?'เลือกเดือน':'เลือกปี'}>{mode==='month'?<input className="input" type="month" value={period} onChange={e=>setPeriod(e.target.value)}/>:<input className="input" type="number" min="2000" max="2100" value={period} onChange={e=>setPeriod(e.target.value)} />}</Field><Field label="ทะเบียนรถ"><select className="input" value={vehicleId} onChange={e=>setVehicleId(e.target.value)}><option value="all">ทุกคัน</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate_no}</option>)}</select></Field><button className="ktf-refresh" onClick={load} disabled={loading}><RotateCcw size={17}/>{loading?'กำลังโหลด':'รีเฟรช'}</button><button className="ktf-download" onClick={()=>exportCsv(rows,period)} disabled={!rows.length}><Download size={17}/> CSV</button></section>
    <p className="ktf-note">สาขา {activeBranch?.name||'-'} · สรุปเฉพาะเที่ยวที่บันทึกในเมนูนี้ ไม่รวมบัญชีขนส่งหรืองานน้ำมันเดิมอัตโนมัติ เพื่อไม่ให้นับรายรับรายจ่ายซ้ำ</p>
    <section className="ktf-totals"><MoneyCard label="รายรับค่าขนส่ง" value={summary.income_satang} kind="income"/><MoneyCard label="รวมต้นทุนทุกเที่ยว" value={summary.expense_satang} kind="expense"/><MoneyCard label="กำไร / ขาดทุน" value={summary.profit_satang} kind={summary.profit_satang<0?'negative':'profit'}/></section>
    <section className="ktf-panel ktf-editor" ref={editor}><div className="ktf-heading"><div><span>01 / TRIP DETAILS</span><h2>{editing?'แก้ไขบัญชีเที่ยว':'เพิ่มบัญชีเที่ยวใหม่'}</h2><p>กรอกทีละเที่ยว ระบบจะรวมต้นทุนและคำนวณกำไร/ขาดทุนให้อัตโนมัติ</p></div>{editing&&<button type="button" className="ktf-link" onClick={reset}><X size={17}/> ยกเลิกแก้ไข</button>}</div><form onSubmit={save} className="ktf-form">
      <Field label="วันที่เที่ยว *"><input className="input" type="date" required value={form.date} onChange={e=>field('date',e.target.value)}/></Field><Field label="ทะเบียนรถ *"><select className="input" required value={form.vehicle_id} onChange={e=>field('vehicle_id',e.target.value)}><option value="">เลือกทะเบียนรถ</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate_no}</option>)}</select></Field>
      <Field label="วัสดุที่ขน *"><input className="input" required list="ktf-materials" maxLength={120} value={form.material} onChange={e=>field('material',e.target.value)} placeholder="เลือกหรือพิมพ์ เช่น ทราย / หิน"/><datalist id="ktf-materials">{['ทราย','หิน','ดิน','ปูน','หินคลุก','ทรายถม'].map(v=><option key={v} value={v}/>)}</datalist></Field><Field label="น้ำหนัก / จำนวน"><input className="input" value={form.quantity} onChange={e=>field('quantity',e.target.value)} placeholder="เช่น 30 ตัน" maxLength={80}/></Field>
      <Field label="ต้นทาง"><input className="input" value={form.origin_place} onChange={e=>field('origin_place',e.target.value)} placeholder="จุดรับสินค้า" maxLength={200}/></Field><Field label="ปลายทาง"><input className="input" value={form.destination_place} onChange={e=>field('destination_place',e.target.value)} placeholder="จุดส่งสินค้า" maxLength={200}/></Field>
      <Field label="ระยะทางที่กรอกเอง (กม.)"><input className="input" type="number" min="0" max="1000000" step="0.01" value={form.distance_km} onChange={e=>field('distance_km',e.target.value)} placeholder="0.00"/></Field><Field label="เลขที่ใบงาน / เอกสาร"><input className="input" value={form.reference} onChange={e=>field('reference',e.target.value)} placeholder="ถ้ามี" maxLength={90}/></Field>
      <div className="ktf-subhead"><Wallet size={19}/><div><strong>รายรับต่อเที่ยว</strong><small>กรอกยอดค่าขนส่งที่ได้รับหรือคาดว่าจะได้รับ</small></div></div>
      <Field label="ค่าขนส่ง (บาท) *" className="ktf-highlight"><input className="input" required type="number" min="0" max="9999999999.99" step="0.01" value={form.income_baht} onChange={e=>field('income_baht',e.target.value)} placeholder="0.00" /></Field>
      <div className="ktf-subhead"><Truck size={19}/><div><strong>ต้นทุนของเที่ยวนี้</strong><small>เว้นว่างได้ถ้าไม่มีค่าใช้จ่ายในหมวดนั้น</small></div></div>
      {costs.map(([key,label])=><Field label={`${label} (บาท)`} key={key}><input className="input" type="number" min="0" max="9999999999.99" step="0.01" value={form[key]} onChange={e=>field(key,e.target.value)} placeholder="0.00"/></Field>)}
      <Field label="หมายเหตุ" className="ktf-wide"><textarea className="input" rows={2} maxLength={500} value={form.note} onChange={e=>field('note',e.target.value)} placeholder="รายละเอียดเพิ่มเติม"/></Field>
      <div className="ktf-preview ktf-wide"><div><span>รายรับ</span><strong>{baht(income/100)} ฿</strong></div><div><span>ต้นทุนรวม</span><strong>{baht(costTotal/100)} ฿</strong></div><div className={income-costTotal<0?'loss':''}><span>กำไร / ขาดทุนต่อเที่ยว</span><strong>{baht((income-costTotal)/100)} ฿</strong></div></div>
      <div className="ktf-submit ktf-wide"><button type="submit" className="btn-primary" disabled={saving||!vehicles.length}><Save size={18}/>{saving?'กำลังบันทึก...':editing?'บันทึกการแก้ไข':'บันทึกบัญชีเที่ยว'}</button>{!vehicles.length&&<small>เพิ่มทะเบียนรถในเมนูรถและคนขับก่อนบันทึก</small>}</div>
    </form></section>
    <section className="ktf-panel"><div className="ktf-heading"><div><span>02 / VEHICLE REPORT</span><h2>สรุปกำไร / ขาดทุนต่อคัน</h2><p>{mode==='month'?`เดือน ${period}`:`ปี ${period}`} · รายรับ − ค่าใช้จ่าย</p></div></div><div className="ktf-table-wrap"><table><thead><tr><th>ทะเบียนรถ</th><th>เที่ยว</th><th>รายรับ</th><th>รายจ่าย</th><th>กำไร/ขาดทุน</th></tr></thead><tbody>{(data?.by_vehicle||[]).filter(v=>vehicleId==='all'||v.vehicle_id===vehicleId).map(v=><tr key={v.vehicle_id}><td><strong>{v.plate_no}</strong></td><td>{v.trips}</td><td>{money(v.income_satang)} ฿</td><td>{money(v.expense_satang)} ฿</td><td className={v.profit_satang<0?'ktf-loss':'ktf-gain'}>{money(v.profit_satang)} ฿</td></tr>)}</tbody></table></div></section>
    {mode==='year'&&<section className="ktf-panel"><div className="ktf-heading"><div><span>03 / YEAR BREAKDOWN</span><h2>รายเดือนในปี {period}</h2><p>ดูยอดรับ–จ่ายและกำไรในแต่ละเดือนของปีที่เลือก</p></div></div><div className="ktf-table-wrap"><table><thead><tr><th>เดือน</th><th>เที่ยว</th><th>รายรับ</th><th>รายจ่าย</th><th>กำไร/ขาดทุน</th></tr></thead><tbody>{(vehicleId==='all'?(data?.by_month||[]):Object.entries(rows.reduce((a,r)=>{const m=r.date.slice(0,7);const t=a[m]||(a[m]={month:m,trips:0,income_satang:0,expense_satang:0,profit_satang:0});t.trips++;t.income_satang+=r.income_satang;t.expense_satang+=r.expense_satang;t.profit_satang+=r.profit_satang;return a;},{})).map(([,v])=>v).sort((a,b)=>b.month.localeCompare(a.month))).map(v=><tr key={v.month}><td>{v.month}</td><td>{v.trips}</td><td>{money(v.income_satang)} ฿</td><td>{money(v.expense_satang)} ฿</td><td className={v.profit_satang<0?'ktf-loss':'ktf-gain'}>{money(v.profit_satang)} ฿</td></tr>)}</tbody></table></div></section>}
    <section className="ktf-panel"><div className="ktf-heading"><div><span>04 / TRIP HISTORY</span><h2>เที่ยวงานที่บันทึกไว้</h2><p>{rows.length} เที่ยว · เลือกรายการเพื่อแก้ไขหรือลบ</p></div><button className="ktf-download" onClick={()=>exportCsv(rows,period)} disabled={!rows.length}><Download size={16}/> ส่งออก</button></div><div className="ktf-trip-list">{rows.map(r=><article className="ktf-trip" key={r.id}><div className="ktf-trip-head"><div><span>{r.date} · {r.reference||'เที่ยวงาน'}</span><h3>{r.plate_no} · {r.material}</h3><p>{r.origin_place||'ไม่ระบุต้นทาง'} → {r.destination_place||'ไม่ระบุปลายทาง'} · {r.quantity||'-'} · {r.distance_km||0} กม.</p></div><div className={r.profit_satang<0?'ktf-loss':'ktf-gain'}><small>กำไร/ขาดทุน</small><strong>{money(r.profit_satang)} ฿</strong></div></div><div className="ktf-trip-money"><span>รายรับ <b>{money(r.income_satang)} ฿</b></span><span>รายจ่าย <b>{money(r.expense_satang)} ฿</b></span></div><details><summary>ดูต้นทุนแยกหมวด <ChevronDown size={16}/></summary><div className="ktf-cost-breakdown">{costs.map(([key,label])=><div key={key}><span>{label}</span><b>{money(r[`${key}_satang`])} ฿</b></div>)}{r.note&&<p className="ktf-wide">หมายเหตุ: {r.note}</p>}</div></details><div className="ktf-trip-actions"><button type="button" onClick={()=>edit(r)}><Pencil size={16}/> แก้ไข</button><button type="button" onClick={()=>remove(r)}><Trash2 size={16}/> ลบ</button></div></article>)}{!rows.length&&<div className="ktf-empty">{loading?'กำลังโหลดรายการ...':'ยังไม่มีข้อมูลเที่ยวงานในช่วงเวลานี้'}</div>}</div></section>
  </div>;
}
